### ISSUE TITLE
Unable to reach app. Please try again

### ISSUE THREAD

**Issue by lihuyn** [OfficeDev/Microsoft-Teams-App-Reflect#13]
![image](https://user-images.githubusercontent.com/70432109/91633638-68267480-ea2d-11ea-8122-01ae74e99345.png)

Hi team, I've followed all steps in the deployment guide, and have tried deploying the Reflect messaging extension twice now. I still get the error "Unable to reach app. Please try again". Can you please provide guidance on how to fix this?

**Comment by userphilw** [comment]
Having the same issue.

**Comment by Darren-Austin** [comment]
Hi @lihuyn & @userphilw - this kind of error is potentially due to a misplaced parameter during the deployment process which is understandable due to the complexity of the deployment process.  We have been working on an automated script to streamline the deployment process and this should be ready to go by tomorrow morning.

**Comment by userphilw** [comment]
Really appreciate it.

**Comment by Darren-Austin** [comment]
Hi @lihuyn & @userphilw - we just updated the deployment guide and the ARM template in the source code.  Please try to deploy again with this new method.  It should resolve the issues you are seeing.

**Comment by lihuyn** [comment]
Thanks for your help, I've successfully deployed it! However, I've noticed a few issues:
1. The logo doesn't appear when the bot is invoked.
2. The reflect messaging extension can't be invoked in any chat/channel e.g. every time I want to send it to a specific person or group chat, I need to go to App Store > Upload a custom app > select the arrow to 'Add to a chat'. This means that every time it is sent to a separate group or channel, the reflect app needs to be re-uploaded, which is very manual and repetitive.
3. Reflect can't be deleted when you click on the 3 dots > More Actions > Remove posts. It just shows a blank white pop up.
Do you have any guidance on the above or is it something that needs to be fixed?

![image](https://user-images.githubusercontent.com/70432109/91986283-0426e780-ed70-11ea-99c2-b4878bfeb443.png)

![image](https://user-images.githubusercontent.com/70432109/91986789-82838980-ed70-11ea-809d-7bc786b1e92f.png)

![image](https://user-images.githubusercontent.com/70432109/91986808-8b745b00-ed70-11ea-9d9b-7d19826811c5.png)

**Comment by Darren-Austin** [comment]
Hi @lihuyn - thank you for the feedback.  The issue with the icon not appearing at first is something we've seen before and should resolve itself after a few hours.  

You need to add Reflect to each chat because it is technically a chat bot.  Teams treats chat bots similar to other users so much like chatting with another user, you need to explicitly add Reflect to each team channel or chat you want to use it in. Once you add it to a team or a chat, though, anyone can use Reflect to create a Reflect poll to check in with the team.

We are looking into a way for Reflect to proactively request to be added to a chat so that it's easier for users to access it. If we are successful at that we will update the code with the new functionality. 

Thank you for reporting the issue with the deleting a post.  We will investigate that.

**Comment by ersoon** [comment]
Hi @Darren-Austin, 

I'm getting a similar problem to lihuyn whereby I'm unable to reach the app after deploying it multiple times. I've followed the new deployment guide and also leveraged the new ARM template in the source code. I was wondering if you were able to provide further guidance on how this issue can be addressed? :) 

Thank you!

**Comment by Darren-Austin** [comment]
Hi @ersoon . This error indicates that the Reflect app in Teams is not able to communicate with the bot service in Azure.  From what we've seen so far, the two most common reasons this could be the case are:
1. The Azure account is out of funds or the free trial period has expired.  
2. The tenant type was set to "single tenant" in step 1.2.  

The first possibility should be easy enough to check on so I'll focus on how to troubleshoot the second item.  To do this, in the Azure portal navigate to the Reflect app registration you created for Reflect and make sure that the "Supported account types" setting is set to Multitenant.  (see the "Caution" note after step 3.5 for a screen shot for what to look for.)  While Reflect is technically capable of functioning if deployed for a single tenant environment, when deployed that way we have frequently seen the error you are seeing and switching the setting to "multitenant" solves the issue.  

Hope this helps and resolves the issue.  Please reply here to let us know either way.

**Comment by ersoon** [comment]
Hi @Darren-Austin - thank you for getting back to me so quick! I've double checked and I have the setting set to 'Multiple Organisations' + enough Azure credit to deploy Reflect but unfortunately, I still get the error when I try to deploy it. 

I will try again later this week and hopefully it will work out! 
![image](https://user-images.githubusercontent.com/71808860/94392035-82718080-019a-11eb-8a49-35098d596837.png)

**Comment by xrysmu-bsd** [comment]
> 
> 
> Hi @ersoon . This error indicates that the Reflect app in Teams is not able to communicate with the bot service in Azure. From what we've seen so far, the two most common reasons this could be the case are:
> 
>     1. The Azure account is out of funds or the free trial period has expired.
> 
>     2. The tenant type was set to "single tenant" in step 1.2.
> 
> 
> The first possibility should be easy enough to check on so I'll focus on how to troubleshoot the second item. To do this, in the Azure portal navigate to the Reflect app registration you created for Reflect and make sure that the "Supported account types" setting is set to Multitenant. (see the "Caution" note after step 3.5 for a screen shot for what to look for.) While Reflect is technically capable of functioning if deployed for a single tenant environment, when deployed that way we have frequently seen the error you are seeing and switching the setting to "multitenant" solves the issue.
> 
> Hope this helps and resolves the issue. Please reply here to let us know either way.

Darren,
I was getting the same "unable to reach app" error.  I switched from single tenant to multi-tenant and am still getting the error and the resource group is associated with a "pay as you go" subscription so I don't think that is the issue.  Would I need to re-deploy after the tenancy switch and/or do I need to regenerate the manifest?  Thanks,
Chris

**Comment by xrysmu-bsd** [comment]
@Darren-Austin ,
I redeployed the app, switching it to Multi-tenant and making sure it is associated with our "pay as you go" subscription.  The reflect comes up in Teams and I can assign it to a channel or chat but when I created a reflection/question no one in the channel or in the chat gets the reflection and I don't see it in the chat thread.  Would there be some Azure setting(s) that I should check to make sure there isn't a restriction on the bot? Thanks.
Chris

**Comment by Darren-Austin** [comment]
Hi @xrysmu-bsd - just to clarify, when you invoke Reflect you see the pop up modal with the form where you can customize the Reflect poll (see image below) but after you click "send" nothing appears in the chat thread?
<img width="1366" alt="Posting a reflect poll 2" src="https://user-images.githubusercontent.com/9708624/95634496-e4ee3a80-0a3e-11eb-8031-614a7990b374.png">

The only reason I can think of that would cause this is if Reflect is somehow not added to that specific channel or chat.  Maybe double check that Reflect is showing up as having been installed in that team.  To do that, go to the Manage Team screen and select the Apps tab.  Double check that Reflect appears in that list. 

![Reflect app in team](https://user-images.githubusercontent.com/9708624/95636935-529d6500-0a45-11eb-81cd-b664a40bfbad.png)

**Comment by Christo1986** [comment]
Hi, i have now tried about 6 times to install reflect on my Teams and i keep getting "Unable to reach app. Please try again" I have a new registration of Azure on the free plan so it's still valid for 12 months. I have followed the instructions and applied every step exactly. My Tenant type is set to Multitenant. I'm at my end with this installation.

**Comment by ChrisRobb93** [comment]
Hi @Darren-Austin - I am seeing the "Unable to reach app. Please try again." message as well.
We can see the application has been assigned to the team, we are able to query the bot and complete the form for the Reflect, when I hit **confirm** it spins for a few seconds then gives me the error.
I can confirm we have the app set to Multi Tenant and using the "Free" tier for Bot Service Plan
